// Generates lib/src/locale_direction_data.dart from Unicode CLDR data.
//
// Usage: dart run tool/generate_locale_direction.dart
//
// The data comes from the CLDR release that matches the pinned LDML version
// ([cldrTag]). Moving the pin (#10) updates the tag and reruns this script.

import 'dart:convert';
import 'dart:io';

/// The CLDR tag of the pinned LDML version.
const cldrTag = 'release-48-2';

const _base = 'https://raw.githubusercontent.com/unicode-org/cldr/$cldrTag';

Future<void> main() async {
  final scriptMetadata =
      await _fetch('$_base/common/properties/scriptMetadata.txt');
  final likelySubtags =
      await _fetch('$_base/common/supplemental/likelySubtags.xml');
  final metadata = await _fetch('$_base/common/supplemental/'
      'supplementalMetadata.xml');
  final license = await _fetch('$_base/LICENSE');

  // Field 6 of scriptMetadata.txt is whether the script is right-to-left.
  final rtlScripts = <String>{
    for (final line in LineSplitter.split(scriptMetadata))
      if (line.isNotEmpty && !line.startsWith('#'))
        if (line.split(';').map((field) => field.trim()).toList()
            case [final script, _, _, _, _, _, 'YES', ...])
          script.toLowerCase(),
  };

  // Likely subtags of a language, or of a language and region, without a
  // script: `from` is `lang` or `lang_REGION`. The language can be `und`,
  // so that a region alone, as in `und-SA`, finds its likely script.
  final likelyRtl = <String, bool>{};
  // The likely region of each language, for choosing among the replacements
  // of a deprecated region.
  final likelyRegion = <String, String>{};
  final entry = RegExp(r'<likelySubtag from="([^"]+)" to="([^"]+)"');
  for (final match in entry.allMatches(likelySubtags)) {
    final from = match[1]!.split('_');
    final to = match[2]!.split('_');
    if (from.any((s) => s.length == 4)) continue;
    if (to.length != 3) continue;
    likelyRtl[from.join('-').toLowerCase()] =
        rtlScripts.contains(to[1].toLowerCase());
    if (from.length == 1) likelyRegion[from.first] = to[2].toLowerCase();
  }

  // A language and region is listed only where its direction differs from
  // the language's.
  final rtlLanguages = {
    for (final MapEntry(:key, :value) in likelyRtl.entries)
      if (!key.contains('-') && value) key,
  };
  final regionOverrides = {
    for (final MapEntry(:key, :value) in likelyRtl.entries)
      if (key.contains('-') &&
          value != rtlLanguages.contains(key.split('-').first))
        key: value,
  };

  // A deprecated region, such as `YD`, takes the direction of its
  // replacement. Where it has several, UTS #35 canonicalization picks the
  // language's likely region if it is one of them, and otherwise the first.
  // Only codes that are valid region subtags, two letters or three digits,
  // are kept; the three-letter ISO 3166 codes cannot appear in a tag.
  final territoryAlias = RegExp(
      r'<territoryAlias type="([A-Z]{2}|[0-9]{3})" replacement="([A-Z0-9 ]+)"');
  final aliasOverrides = <String, bool>{};
  for (final match in territoryAlias.allMatches(metadata)) {
    final deprecated = match[1]!.toLowerCase();
    final replacements = match[2]!.toLowerCase().split(' ');
    for (final MapEntry(:key, :value) in regionOverrides.entries) {
      final [language, region] = key.split('-');
      final likely = likelyRegion[language];
      final chosen =
          replacements.contains(likely) ? likely : replacements.first;
      final aliasKey = '$language-$deprecated';
      if (chosen == region && !likelyRtl.containsKey(aliasKey)) {
        aliasOverrides[aliasKey] = value;
      }
    }
  }
  regionOverrides.addAll(aliasOverrides);

  // The direction of a replacement locale such as `he`, `fa_AF`, or
  // `sr_Latn`: its script if it has one, otherwise the likely script of its
  // language and region.
  bool isRtl(String locale) {
    final [language, ...rest] = locale.toLowerCase().split('_');
    String? region;
    for (final subtag in rest) {
      if (subtag.length == 4) return rtlScripts.contains(subtag);
      if (subtag.length == 2 || int.tryParse(subtag) != null) {
        region = subtag;
        break;
      }
    }
    return likelyRtl['$language-$region'] ?? likelyRtl[language] ?? false;
  }

  // Deprecated language codes whose replacement is right-to-left. A code
  // that has likely subtags of its own keeps their direction.
  final alias =
      RegExp(r'<languageAlias type="([a-z]+)" replacement="([A-Za-z0-9_]+)"');
  final rtlAliases = {
    for (final match in alias.allMatches(metadata))
      if (!likelyRtl.containsKey(match[1]) && isRtl(match[2]!)) match[1]!,
  };

  final output = StringBuffer()
    ..writeln('// Generated by tool/generate_locale_direction.dart from')
    ..writeln('// Unicode CLDR $cldrTag. Do not edit.')
    ..writeln('//')
    ..writeln(
        '// The data below is derived from Unicode CLDR data files, which')
    ..writeln('// are distributed under this notice:')
    ..writeln('//')
    ..writeAll([
      for (final line in LineSplitter.split(license.trim()))
        line.isEmpty ? '//\n' : '// $line\n',
    ])
    ..writeln()
    ..writeln('/// ISO 15924 codes, in lowercase, of the scripts that')
    ..writeln('/// `scriptMetadata.txt` marks right-to-left.')
    ..writeln('const rtlScripts = {${_list(rtlScripts)}};')
    ..writeln()
    ..writeln('/// Languages whose likely script, in `likelySubtags.xml`, is')
    ..writeln('/// right-to-left, and deprecated codes whose replacement is.')
    ..writeln(
        'const rtlLanguages = {${_list({...rtlLanguages, ...rtlAliases})}};')
    ..writeln()
    ..writeln('/// Languages and regions, as `lang-region` in lowercase, whose')
    ..writeln(
        '/// likely script has a different direction from the language\'s:')
    ..writeln('/// `true` for right-to-left.')
    ..writeln('const regionDirectionOverrides = {')
    ..writeAll([
      for (final key in regionOverrides.keys.toList()..sort())
        "  '$key': ${regionOverrides[key]},\n",
    ])
    ..writeln('};');

  final file = File.fromUri(
      Platform.script.resolve('../lib/src/locale_direction_data.dart'));
  file.writeAsStringSync(output.toString());
  final format = Process.runSync('dart', ['format', file.path]);
  stdout.write(format.stdout);
  stderr.write(format.stderr);
}

String _list(Set<String> values) =>
    [for (final value in values.toList()..sort()) "'$value'"].join(', ');

Future<String> _fetch(String url) async {
  final client = HttpClient();
  try {
    final response = await (await client.getUrl(Uri.parse(url))).close();
    if (response.statusCode != HttpStatus.ok) {
      throw HttpException('${response.statusCode} for $url');
    }
    return await response.transform(utf8.decoder).join();
  } finally {
    client.close();
  }
}
