// Generates lib/src/locale_direction_data.dart from Unicode CLDR data.
//
// Usage: dart run tool/generate_locale_direction.dart
//
// The data comes from the CLDR release that matches the pinned LDML version
// ([cldrTag]). Moving the pin (#10) updates the tag and reruns this script.

import 'dart:convert';
import 'dart:io';

/// The CLDR tag of the pinned LDML version.
const cldrTag = 'release-48-2';

const _base = 'https://raw.githubusercontent.com/unicode-org/cldr/$cldrTag';

Future<void> main() async {
  final scriptMetadata =
      await _fetch('$_base/common/properties/scriptMetadata.txt');
  final likelySubtags =
      await _fetch('$_base/common/supplemental/likelySubtags.xml');
  final metadata = await _fetch('$_base/common/supplemental/'
      'supplementalMetadata.xml');
  final license = await _fetch('$_base/LICENSE');

  // Field 6 of scriptMetadata.txt is whether the script is right-to-left.
  final rtlScripts = <String>{
    for (final line in LineSplitter.split(scriptMetadata))
      if (line.isNotEmpty && !line.startsWith('#'))
        if (line.split(';').map((field) => field.trim()).toList()
            case [final script, _, _, _, _, _, 'YES', ...])
          script.toLowerCase(),
  };

  // Likely subtags of a language, or of a language and region, without a
  // script: `from` is `lang` or `lang_REGION`.
  final likelyRtl = <String, bool>{};
  final entry = RegExp(r'<likelySubtag from="([^"]+)" to="([^"]+)"');
  for (final match in entry.allMatches(likelySubtags)) {
    final from = match[1]!.split('_');
    final to = match[2]!.split('_');
    if (from.first == 'und' || from.any((s) => s.length == 4)) continue;
    if (to.length != 3) continue;
    likelyRtl[from.join('-').toLowerCase()] =
        rtlScripts.contains(to[1].toLowerCase());
  }

  // A language and region is listed only where its direction differs from
  // the language's.
  final rtlLanguages = {
    for (final MapEntry(:key, :value) in likelyRtl.entries)
      if (!key.contains('-') && value) key,
  };
  final regionOverrides = {
    for (final MapEntry(:key, :value) in likelyRtl.entries)
      if (key.contains('-') &&
          value != rtlLanguages.contains(key.split('-').first))
        key: value,
  };

  // Deprecated language codes whose replacement is right-to-left.
  final alias =
      RegExp(r'<languageAlias type="([a-z]+)" replacement="([a-z]+)"');
  final rtlAliases = {
    for (final match in alias.allMatches(metadata))
      if (rtlLanguages.contains(match[2]) && !likelyRtl.containsKey(match[1]))
        match[1]!,
  };

  final output = StringBuffer()
    ..writeln('// Generated by tool/generate_locale_direction.dart from')
    ..writeln('// Unicode CLDR $cldrTag. Do not edit.')
    ..writeln('//')
    ..writeln(
        '// The data below is derived from Unicode CLDR data files, which')
    ..writeln('// are distributed under this notice:')
    ..writeln('//')
    ..writeAll([
      for (final line in LineSplitter.split(license.trim()))
        line.isEmpty ? '//\n' : '// $line\n',
    ])
    ..writeln()
    ..writeln('/// ISO 15924 codes, in lowercase, of the scripts that')
    ..writeln('/// `scriptMetadata.txt` marks right-to-left.')
    ..writeln('const rtlScripts = {${_list(rtlScripts)}};')
    ..writeln()
    ..writeln('/// Languages whose likely script, in `likelySubtags.xml`, is')
    ..writeln('/// right-to-left, and deprecated codes whose replacement is.')
    ..writeln(
        'const rtlLanguages = {${_list({...rtlLanguages, ...rtlAliases})}};')
    ..writeln()
    ..writeln('/// Languages and regions, as `lang-region` in lowercase, whose')
    ..writeln(
        '/// likely script has a different direction from the language\'s:')
    ..writeln('/// `true` for right-to-left.')
    ..writeln('const regionDirectionOverrides = {')
    ..writeAll([
      for (final key in regionOverrides.keys.toList()..sort())
        "  '$key': ${regionOverrides[key]},\n",
    ])
    ..writeln('};');

  final file = File.fromUri(
      Platform.script.resolve('../lib/src/locale_direction_data.dart'));
  file.writeAsStringSync(output.toString());
  final format = Process.runSync('dart', ['format', file.path]);
  stdout.write(format.stdout);
  stderr.write(format.stderr);
}

String _list(Set<String> values) =>
    [for (final value in values.toList()..sort()) "'$value'"].join(', ');

Future<String> _fetch(String url) async {
  final client = HttpClient();
  try {
    final response = await (await client.getUrl(Uri.parse(url))).close();
    if (response.statusCode != HttpStatus.ok) {
      throw HttpException('${response.statusCode} for $url');
    }
    return await response.transform(utf8.decoder).join();
  } finally {
    client.close();
  }
}
