// Generated by tool/generate_cldr_data.dart from the CLDR JSON
// packages 48.2.0 (Unicode CLDR release-48-2). Do not edit.
//
// The data below is derived from Unicode CLDR data files, which
// are distributed under this notice:
//
// UNICODE LICENSE V3
//
// COPYRIGHT AND PERMISSION NOTICE
//
// Copyright © 2004-2026 Unicode, Inc.
//
// NOTICE TO USER: Carefully read the following legal agreement. BY
// DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
// SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
// TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
// DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of data files and any associated documentation (the "Data Files") or
// software and any associated documentation (the "Software") to deal in the
// Data Files or Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, and/or sell
// copies of the Data Files or Software, and to permit persons to whom the
// Data Files or Software are furnished to do so, provided that either (a)
// this copyright and permission notice appear with all copies of the Data
// Files or Software, or (b) this copyright and permission notice appear in
// associated Documentation.
//
// THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
// KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
// THIRD PARTY RIGHTS.
//
// IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
// BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
// OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
// WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
// ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
// FILES OR SOFTWARE.
//
// Except as contained in this notice, the name of a copyright holder shall
// not be used in advertising or otherwise to promote the sale, use or other
// dealings in these Data Files or Software without prior written
// authorization of the copyright holder.
//
// SPDX-License-Identifier: Unicode-3.0

import 'plural_rules.dart';

String _cardinal0(PluralOperands o) {
  if (o.t == 0 && o.i == 1) {
    return 'one';
  }
  return 'other';
}

String _cardinal1(PluralOperands o) {
  if (o.t == 0 && o.i <= 1) {
    return 'one';
  }
  return 'other';
}

String _cardinal2(PluralOperands o) {
  if (o.i == 0 || (o.t == 0 && o.i == 1)) {
    return 'one';
  }
  return 'other';
}

String _cardinal3(PluralOperands o) {
  if (o.t == 0 && o.i == 0) {
    return 'zero';
  }
  if (o.t == 0 && o.i == 1) {
    return 'one';
  }
  if (o.t == 0 && o.i == 2) {
    return 'two';
  }
  if (o.t == 0 && (o.i % 100 >= 3 && o.i % 100 <= 10)) {
    return 'few';
  }
  if (o.t == 0 && (o.i % 100 >= 11 && o.i % 100 <= 99)) {
    return 'many';
  }
  return 'other';
}

String _cardinal4(PluralOperands o) {
  if (o.i == 1 && o.v == 0) {
    return 'one';
  }
  return 'other';
}

String _cardinal5(PluralOperands o) {
  if (o.t == 0 && o.i % 10 == 1 && !(o.t == 0 && o.i % 100 == 11)) {
    return 'one';
  }
  if (o.t == 0 &&
      (o.i % 10 >= 2 && o.i % 10 <= 4) &&
      !(o.t == 0 && (o.i % 100 >= 12 && o.i % 100 <= 14))) {
    return 'few';
  }
  if ((o.t == 0 && o.i % 10 == 0) ||
      (o.t == 0 && (o.i % 10 >= 5 && o.i % 10 <= 9)) ||
      (o.t == 0 && (o.i % 100 >= 11 && o.i % 100 <= 14))) {
    return 'many';
  }
  return 'other';
}

String _cardinal6(PluralOperands o) {
  if (o.t == 0 && o.i == 0) {
    return 'zero';
  }
  if (o.t == 0 && o.i == 1) {
    return 'one';
  }
  return 'other';
}

String _cardinal7(PluralOperands o) {
  return 'other';
}

String _cardinal8(PluralOperands o) {
  if (o.t == 0 &&
      o.i % 10 == 1 &&
      !(o.t == 0 && (o.i % 100 == 11 || o.i % 100 == 71 || o.i % 100 == 91))) {
    return 'one';
  }
  if (o.t == 0 &&
      o.i % 10 == 2 &&
      !(o.t == 0 && (o.i % 100 == 12 || o.i % 100 == 72 || o.i % 100 == 92))) {
    return 'two';
  }
  if (o.t == 0 &&
      ((o.i % 10 >= 3 && o.i % 10 <= 4) || o.i % 10 == 9) &&
      !(o.t == 0 &&
          ((o.i % 100 >= 10 && o.i % 100 <= 19) ||
              (o.i % 100 >= 70 && o.i % 100 <= 79) ||
              (o.i % 100 >= 90 && o.i % 100 <= 99)))) {
    return 'few';
  }
  if (!(o.t == 0 && o.i == 0) && o.t == 0 && o.i % 1000000 == 0) {
    return 'many';
  }
  return 'other';
}

String _cardinal9(PluralOperands o) {
  if ((o.v == 0 && o.i % 10 == 1 && !(o.i % 100 == 11)) ||
      (o.f % 10 == 1 && !(o.f % 100 == 11))) {
    return 'one';
  }
  if ((o.v == 0 &&
          o.i % 10 >= 2 &&
          o.i % 10 <= 4 &&
          !(o.i % 100 >= 12 && o.i % 100 <= 14)) ||
      (o.f % 10 >= 2 &&
          o.f % 10 <= 4 &&
          !(o.f % 100 >= 12 && o.f % 100 <= 14))) {
    return 'few';
  }
  return 'other';
}

String _cardinal10(PluralOperands o) {
  if (o.i == 1 && o.v == 0) {
    return 'one';
  }
  if (!(o.i == 0) && o.i % 1000000 == 0 && o.v == 0) {
    return 'many';
  }
  return 'other';
}

String _cardinal11(PluralOperands o) {
  if ((o.v == 0 && (o.i == 1 || o.i == 2 || o.i == 3)) ||
      (o.v == 0 && !(o.i % 10 == 4 || o.i % 10 == 6 || o.i % 10 == 9)) ||
      (!(o.v == 0) && !(o.f % 10 == 4 || o.f % 10 == 6 || o.f % 10 == 9))) {
    return 'one';
  }
  return 'other';
}

String _cardinal12(PluralOperands o) {
  if (o.i == 1 && o.v == 0) {
    return 'one';
  }
  if (o.i >= 2 && o.i <= 4 && o.v == 0) {
    return 'few';
  }
  if (!(o.v == 0)) {
    return 'many';
  }
  return 'other';
}

String _cardinal13(PluralOperands o) {
  if (o.t == 0 && o.i == 0) {
    return 'zero';
  }
  if (o.t == 0 && o.i == 1) {
    return 'one';
  }
  if (o.t == 0 && o.i == 2) {
    return 'two';
  }
  if (o.t == 0 && o.i == 3) {
    return 'few';
  }
  if (o.t == 0 && o.i == 6) {
    return 'many';
  }
  return 'other';
}

String _cardinal14(PluralOperands o) {
  if ((o.t == 0 && o.i == 1) || (!(o.t == 0) && (o.i == 0 || o.i == 1))) {
    return 'one';
  }
  return 'other';
}

String _cardinal15(PluralOperands o) {
  if ((o.v == 0 && o.i % 100 == 1) || o.f % 100 == 1) {
    return 'one';
  }
  if ((o.v == 0 && o.i % 100 == 2) || o.f % 100 == 2) {
    return 'two';
  }
  if ((o.v == 0 && o.i % 100 >= 3 && o.i % 100 <= 4) ||
      (o.f % 100 >= 3 && o.f % 100 <= 4)) {
    return 'few';
  }
  return 'other';
}

String _cardinal16(PluralOperands o) {
  if (o.t == 0 && o.i == 1) {
    return 'one';
  }
  if (!(o.i == 0) && o.i % 1000000 == 0 && o.v == 0) {
    return 'many';
  }
  return 'other';
}

String _cardinal17(PluralOperands o) {
  if ((o.i == 0 || o.i == 1)) {
    return 'one';
  }
  return 'other';
}

String _cardinal18(PluralOperands o) {
  if ((o.i == 0 || o.i == 1)) {
    return 'one';
  }
  if (!(o.i == 0) && o.i % 1000000 == 0 && o.v == 0) {
    return 'many';
  }
  return 'other';
}

String _cardinal19(PluralOperands o) {
  if (o.t == 0 && o.i == 1) {
    return 'one';
  }
  if (o.t == 0 && o.i == 2) {
    return 'two';
  }
  if (o.t == 0 && (o.i >= 3 && o.i <= 6)) {
    return 'few';
  }
  if (o.t == 0 && (o.i >= 7 && o.i <= 10)) {
    return 'many';
  }
  return 'other';
}

String _cardinal20(PluralOperands o) {
  if (o.t == 0 && (o.i == 1 || o.i == 11)) {
    return 'one';
  }
  if (o.t == 0 && (o.i == 2 || o.i == 12)) {
    return 'two';
  }
  if (o.t == 0 && ((o.i >= 3 && o.i <= 10) || (o.i >= 13 && o.i <= 19))) {
    return 'few';
  }
  return 'other';
}

String _cardinal21(PluralOperands o) {
  if (o.v == 0 && o.i % 10 == 1) {
    return 'one';
  }
  if (o.v == 0 && o.i % 10 == 2) {
    return 'two';
  }
  if (o.v == 0 &&
      (o.i % 100 == 0 ||
          o.i % 100 == 20 ||
          o.i % 100 == 40 ||
          o.i % 100 == 60 ||
          o.i % 100 == 80)) {
    return 'few';
  }
  if (!(o.v == 0)) {
    return 'many';
  }
  return 'other';
}

String _cardinal22(PluralOperands o) {
  if ((o.i == 1 && o.v == 0) || (o.i == 0 && !(o.v == 0))) {
    return 'one';
  }
  if (o.i == 2 && o.v == 0) {
    return 'two';
  }
  return 'other';
}

String _cardinal23(PluralOperands o) {
  if ((o.t == 0 && o.i % 10 == 1 && !(o.i % 100 == 11)) ||
      (o.t % 10 == 1 && !(o.t % 100 == 11))) {
    return 'one';
  }
  return 'other';
}

String _cardinal24(PluralOperands o) {
  if (o.t == 0 && o.i == 1) {
    return 'one';
  }
  if (o.t == 0 && o.i == 2) {
    return 'two';
  }
  return 'other';
}

String _cardinal25(PluralOperands o) {
  if (o.t == 0 && o.i == 0) {
    return 'zero';
  }
  if (o.t == 0 && o.i == 1) {
    return 'one';
  }
  if ((o.t == 0 &&
          (o.i % 100 == 2 ||
              o.i % 100 == 22 ||
              o.i % 100 == 42 ||
              o.i % 100 == 62 ||
              o.i % 100 == 82)) ||
      (o.t == 0 &&
          o.i % 1000 == 0 &&
          o.t == 0 &&
          ((o.i % 100000 >= 1000 && o.i % 100000 <= 20000) ||
              o.i % 100000 == 40000 ||
              o.i % 100000 == 60000 ||
              o.i % 100000 == 80000)) ||
      (!(o.t == 0 && o.i == 0) && o.t == 0 && o.i % 1000000 == 100000)) {
    return 'two';
  }
  if (o.t == 0 &&
      (o.i % 100 == 3 ||
          o.i % 100 == 23 ||
          o.i % 100 == 43 ||
          o.i % 100 == 63 ||
          o.i % 100 == 83)) {
    return 'few';
  }
  if (!(o.t == 0 && o.i == 1) &&
      o.t == 0 &&
      (o.i % 100 == 1 ||
          o.i % 100 == 21 ||
          o.i % 100 == 41 ||
          o.i % 100 == 61 ||
          o.i % 100 == 81)) {
    return 'many';
  }
  return 'other';
}

String _cardinal26(PluralOperands o) {
  if (o.t == 0 && o.i == 0) {
    return 'zero';
  }
  if ((o.i == 0 || o.i == 1) && !(o.t == 0 && o.i == 0)) {
    return 'one';
  }
  return 'other';
}

String _cardinal27(PluralOperands o) {
  if (o.t == 0 &&
      o.i % 10 == 1 &&
      !(o.t == 0 && (o.i % 100 >= 11 && o.i % 100 <= 19))) {
    return 'one';
  }
  if (o.t == 0 &&
      (o.i % 10 >= 2 && o.i % 10 <= 9) &&
      !(o.t == 0 && (o.i % 100 >= 11 && o.i % 100 <= 19))) {
    return 'few';
  }
  if (!(o.f == 0)) {
    return 'many';
  }
  return 'other';
}

String _cardinal28(PluralOperands o) {
  if ((o.t == 0 && o.i % 10 == 0) ||
      (o.t == 0 && (o.i % 100 >= 11 && o.i % 100 <= 19)) ||
      (o.v == 2 && o.f % 100 >= 11 && o.f % 100 <= 19)) {
    return 'zero';
  }
  if ((o.t == 0 && o.i % 10 == 1 && !(o.t == 0 && o.i % 100 == 11)) ||
      (o.v == 2 && o.f % 10 == 1 && !(o.f % 100 == 11)) ||
      (!(o.v == 2) && o.f % 10 == 1)) {
    return 'one';
  }
  return 'other';
}

String _cardinal29(PluralOperands o) {
  if ((o.v == 0 && o.i % 10 == 1 && !(o.i % 100 == 11)) ||
      (o.f % 10 == 1 && !(o.f % 100 == 11))) {
    return 'one';
  }
  return 'other';
}

String _cardinal30(PluralOperands o) {
  if (o.i == 1 && o.v == 0) {
    return 'one';
  }
  if (!(o.v == 0) ||
      (o.t == 0 && o.i == 0) ||
      (!(o.t == 0 && o.i == 1) &&
          o.t == 0 &&
          (o.i % 100 >= 1 && o.i % 100 <= 19))) {
    return 'few';
  }
  return 'other';
}

String _cardinal31(PluralOperands o) {
  if (o.t == 0 && o.i == 1) {
    return 'one';
  }
  if (o.t == 0 && o.i == 2) {
    return 'two';
  }
  if ((o.t == 0 && o.i == 0) ||
      (o.t == 0 && (o.i % 100 >= 3 && o.i % 100 <= 10))) {
    return 'few';
  }
  if (o.t == 0 && (o.i % 100 >= 11 && o.i % 100 <= 19)) {
    return 'many';
  }
  return 'other';
}

String _cardinal32(PluralOperands o) {
  if (o.i == 1 && o.v == 0) {
    return 'one';
  }
  if (o.v == 0 &&
      o.i % 10 >= 2 &&
      o.i % 10 <= 4 &&
      !(o.i % 100 >= 12 && o.i % 100 <= 14)) {
    return 'few';
  }
  if ((o.v == 0 && !(o.i == 1) && o.i % 10 <= 1) ||
      (o.v == 0 && o.i % 10 >= 5 && o.i % 10 <= 9) ||
      (o.v == 0 && o.i % 100 >= 12 && o.i % 100 <= 14)) {
    return 'many';
  }
  return 'other';
}

String _cardinal33(PluralOperands o) {
  if (o.i <= 1) {
    return 'one';
  }
  if (!(o.i == 0) && o.i % 1000000 == 0 && o.v == 0) {
    return 'many';
  }
  return 'other';
}

String _cardinal34(PluralOperands o) {
  if (o.v == 0 && o.i % 10 == 1 && !(o.i % 100 == 11)) {
    return 'one';
  }
  if (o.v == 0 &&
      o.i % 10 >= 2 &&
      o.i % 10 <= 4 &&
      !(o.i % 100 >= 12 && o.i % 100 <= 14)) {
    return 'few';
  }
  if ((o.v == 0 && o.i % 10 == 0) ||
      (o.v == 0 && o.i % 10 >= 5 && o.i % 10 <= 9) ||
      (o.v == 0 && o.i % 100 >= 11 && o.i % 100 <= 14)) {
    return 'many';
  }
  return 'other';
}

String _cardinal35(PluralOperands o) {
  if (o.t == 0 && o.i % 10 == 1 && !(o.t == 0 && o.i % 100 == 11)) {
    return 'one';
  }
  if (o.t == 0 && o.i == 2) {
    return 'two';
  }
  if (!(o.t == 0 && o.i == 2) &&
      o.t == 0 &&
      (o.i % 10 >= 2 && o.i % 10 <= 9) &&
      !(o.t == 0 && (o.i % 100 >= 11 && o.i % 100 <= 19))) {
    return 'few';
  }
  if (!(o.f == 0)) {
    return 'many';
  }
  return 'other';
}

String _cardinal36(PluralOperands o) {
  if (o.i == 0 || (o.t == 0 && o.i == 1)) {
    return 'one';
  }
  if (o.t == 0 && (o.i >= 2 && o.i <= 10)) {
    return 'few';
  }
  return 'other';
}

String _cardinal37(PluralOperands o) {
  if ((o.t == 0 && (o.i == 0 || o.i == 1)) || (o.i == 0 && o.f == 1)) {
    return 'one';
  }
  return 'other';
}

String _cardinal38(PluralOperands o) {
  if (o.v == 0 && o.i % 100 == 1) {
    return 'one';
  }
  if (o.v == 0 && o.i % 100 == 2) {
    return 'two';
  }
  if ((o.v == 0 && o.i % 100 >= 3 && o.i % 100 <= 4) || !(o.v == 0)) {
    return 'few';
  }
  return 'other';
}

String _cardinal39(PluralOperands o) {
  if ((o.t == 0 && o.i <= 1) || (o.t == 0 && (o.i >= 11 && o.i <= 99))) {
    return 'one';
  }
  return 'other';
}

/// The CLDR cardinal plural rules, by locale.
const cardinalRules = <String, PluralRule>{
  'af': _cardinal0,
  'ak': _cardinal1,
  'am': _cardinal2,
  'an': _cardinal0,
  'ar': _cardinal3,
  'ars': _cardinal3,
  'as': _cardinal2,
  'asa': _cardinal0,
  'ast': _cardinal4,
  'az': _cardinal0,
  'bal': _cardinal0,
  'be': _cardinal5,
  'bem': _cardinal0,
  'bez': _cardinal0,
  'bg': _cardinal0,
  'bho': _cardinal1,
  'blo': _cardinal6,
  'bm': _cardinal7,
  'bn': _cardinal2,
  'bo': _cardinal7,
  'br': _cardinal8,
  'brx': _cardinal0,
  'bs': _cardinal9,
  'ca': _cardinal10,
  'ce': _cardinal0,
  'ceb': _cardinal11,
  'cgg': _cardinal0,
  'chr': _cardinal0,
  'ckb': _cardinal0,
  'cs': _cardinal12,
  'csw': _cardinal1,
  'cv': _cardinal6,
  'cy': _cardinal13,
  'da': _cardinal14,
  'de': _cardinal4,
  'doi': _cardinal2,
  'dsb': _cardinal15,
  'dv': _cardinal0,
  'dz': _cardinal7,
  'ee': _cardinal0,
  'el': _cardinal0,
  'en': _cardinal4,
  'eo': _cardinal0,
  'es': _cardinal16,
  'et': _cardinal4,
  'eu': _cardinal0,
  'fa': _cardinal2,
  'ff': _cardinal17,
  'fi': _cardinal4,
  'fil': _cardinal11,
  'fo': _cardinal0,
  'fr': _cardinal18,
  'fur': _cardinal0,
  'fy': _cardinal4,
  'ga': _cardinal19,
  'gd': _cardinal20,
  'gl': _cardinal4,
  'gsw': _cardinal0,
  'gu': _cardinal2,
  'guw': _cardinal1,
  'gv': _cardinal21,
  'ha': _cardinal0,
  'haw': _cardinal0,
  'he': _cardinal22,
  'hi': _cardinal2,
  'hnj': _cardinal7,
  'hr': _cardinal9,
  'hsb': _cardinal15,
  'hu': _cardinal0,
  'hy': _cardinal17,
  'ia': _cardinal4,
  'id': _cardinal7,
  'ie': _cardinal4,
  'ig': _cardinal7,
  'ii': _cardinal7,
  'io': _cardinal4,
  'is': _cardinal23,
  'it': _cardinal10,
  'iu': _cardinal24,
  'ja': _cardinal7,
  'jbo': _cardinal7,
  'jgo': _cardinal0,
  'jmc': _cardinal0,
  'jv': _cardinal7,
  'jw': _cardinal7,
  'ka': _cardinal0,
  'kab': _cardinal17,
  'kaj': _cardinal0,
  'kcg': _cardinal0,
  'kde': _cardinal7,
  'kea': _cardinal7,
  'kk': _cardinal0,
  'kkj': _cardinal0,
  'kl': _cardinal0,
  'km': _cardinal7,
  'kn': _cardinal2,
  'ko': _cardinal7,
  'kok': _cardinal2,
  'kok-Latn': _cardinal2,
  'ks': _cardinal0,
  'ksb': _cardinal0,
  'ksh': _cardinal6,
  'ku': _cardinal0,
  'kw': _cardinal25,
  'ky': _cardinal0,
  'lag': _cardinal26,
  'lb': _cardinal0,
  'lg': _cardinal0,
  'lij': _cardinal4,
  'lkt': _cardinal7,
  'lld': _cardinal10,
  'ln': _cardinal1,
  'lo': _cardinal7,
  'lt': _cardinal27,
  'lv': _cardinal28,
  'mas': _cardinal0,
  'mg': _cardinal1,
  'mgo': _cardinal0,
  'mk': _cardinal29,
  'ml': _cardinal0,
  'mn': _cardinal0,
  'mo': _cardinal30,
  'mr': _cardinal0,
  'ms': _cardinal7,
  'mt': _cardinal31,
  'my': _cardinal7,
  'nah': _cardinal0,
  'naq': _cardinal24,
  'nb': _cardinal0,
  'nd': _cardinal0,
  'ne': _cardinal0,
  'nl': _cardinal4,
  'nn': _cardinal0,
  'nnh': _cardinal0,
  'no': _cardinal0,
  'nqo': _cardinal7,
  'nr': _cardinal0,
  'nso': _cardinal1,
  'ny': _cardinal0,
  'nyn': _cardinal0,
  'om': _cardinal0,
  'or': _cardinal0,
  'os': _cardinal0,
  'osa': _cardinal7,
  'pa': _cardinal1,
  'pap': _cardinal0,
  'pcm': _cardinal2,
  'pl': _cardinal32,
  'prg': _cardinal28,
  'ps': _cardinal0,
  'pt': _cardinal33,
  'pt-PT': _cardinal10,
  'rm': _cardinal0,
  'ro': _cardinal30,
  'rof': _cardinal0,
  'ru': _cardinal34,
  'rwk': _cardinal0,
  'sah': _cardinal7,
  'saq': _cardinal0,
  'sat': _cardinal24,
  'sc': _cardinal4,
  'scn': _cardinal10,
  'sd': _cardinal0,
  'sdh': _cardinal0,
  'se': _cardinal24,
  'seh': _cardinal0,
  'ses': _cardinal7,
  'sg': _cardinal7,
  'sgs': _cardinal35,
  'sh': _cardinal9,
  'shi': _cardinal36,
  'si': _cardinal37,
  'sk': _cardinal12,
  'sl': _cardinal38,
  'sma': _cardinal24,
  'smi': _cardinal24,
  'smj': _cardinal24,
  'smn': _cardinal24,
  'sms': _cardinal24,
  'sn': _cardinal0,
  'so': _cardinal0,
  'sq': _cardinal0,
  'sr': _cardinal9,
  'ss': _cardinal0,
  'ssy': _cardinal0,
  'st': _cardinal0,
  'su': _cardinal7,
  'sv': _cardinal4,
  'sw': _cardinal4,
  'syr': _cardinal0,
  'ta': _cardinal0,
  'te': _cardinal0,
  'teo': _cardinal0,
  'th': _cardinal7,
  'ti': _cardinal1,
  'tig': _cardinal0,
  'tk': _cardinal0,
  'tl': _cardinal11,
  'tn': _cardinal0,
  'to': _cardinal7,
  'tpi': _cardinal7,
  'tr': _cardinal0,
  'ts': _cardinal0,
  'tzm': _cardinal39,
  'ug': _cardinal0,
  'uk': _cardinal34,
  'und': _cardinal7,
  'ur': _cardinal4,
  'uz': _cardinal0,
  've': _cardinal0,
  'vec': _cardinal10,
  'vi': _cardinal7,
  'vo': _cardinal0,
  'vun': _cardinal0,
  'wa': _cardinal1,
  'wae': _cardinal0,
  'wo': _cardinal7,
  'xh': _cardinal0,
  'xog': _cardinal0,
  'yi': _cardinal4,
  'yo': _cardinal7,
  'yue': _cardinal7,
  'zh': _cardinal7,
  'zu': _cardinal2,
};

String _ordinal0(PluralOperands o) {
  return 'other';
}

String _ordinal1(PluralOperands o) {
  if (o.t == 0 &&
      (o.i == 1 || o.i == 5 || o.i == 7 || o.i == 8 || o.i == 9 || o.i == 10)) {
    return 'one';
  }
  if (o.t == 0 && (o.i == 2 || o.i == 3)) {
    return 'two';
  }
  if (o.t == 0 && o.i == 4) {
    return 'few';
  }
  if (o.t == 0 && o.i == 6) {
    return 'many';
  }
  return 'other';
}

String _ordinal2(PluralOperands o) {
  if ((o.i % 10 == 1 ||
          o.i % 10 == 2 ||
          o.i % 10 == 5 ||
          o.i % 10 == 7 ||
          o.i % 10 == 8) ||
      (o.i % 100 == 20 ||
          o.i % 100 == 50 ||
          o.i % 100 == 70 ||
          o.i % 100 == 80)) {
    return 'one';
  }
  if ((o.i % 10 == 3 || o.i % 10 == 4) ||
      (o.i % 1000 == 100 ||
          o.i % 1000 == 200 ||
          o.i % 1000 == 300 ||
          o.i % 1000 == 400 ||
          o.i % 1000 == 500 ||
          o.i % 1000 == 600 ||
          o.i % 1000 == 700 ||
          o.i % 1000 == 800 ||
          o.i % 1000 == 900)) {
    return 'few';
  }
  if (o.i == 0 ||
      o.i % 10 == 6 ||
      (o.i % 100 == 40 || o.i % 100 == 60 || o.i % 100 == 90)) {
    return 'many';
  }
  return 'other';
}

String _ordinal3(PluralOperands o) {
  if (o.t == 0 && o.i == 1) {
    return 'one';
  }
  return 'other';
}

String _ordinal4(PluralOperands o) {
  if (o.t == 0 &&
      (o.i % 10 == 2 || o.i % 10 == 3) &&
      !(o.t == 0 && (o.i % 100 == 12 || o.i % 100 == 13))) {
    return 'few';
  }
  return 'other';
}

String _ordinal5(PluralOperands o) {
  if (o.i == 0) {
    return 'zero';
  }
  if (o.i == 1) {
    return 'one';
  }
  if ((o.i == 2 || o.i == 3 || o.i == 4 || o.i == 5 || o.i == 6)) {
    return 'few';
  }
  return 'other';
}

String _ordinal6(PluralOperands o) {
  if (o.t == 0 && (o.i == 1 || o.i == 3)) {
    return 'one';
  }
  if (o.t == 0 && o.i == 2) {
    return 'two';
  }
  if (o.t == 0 && o.i == 4) {
    return 'few';
  }
  return 'other';
}

String _ordinal7(PluralOperands o) {
  if (o.t == 0 && (o.i == 0 || o.i == 7 || o.i == 8 || o.i == 9)) {
    return 'zero';
  }
  if (o.t == 0 && o.i == 1) {
    return 'one';
  }
  if (o.t == 0 && o.i == 2) {
    return 'two';
  }
  if (o.t == 0 && (o.i == 3 || o.i == 4)) {
    return 'few';
  }
  if (o.t == 0 && (o.i == 5 || o.i == 6)) {
    return 'many';
  }
  return 'other';
}

String _ordinal8(PluralOperands o) {
  if (o.t == 0 && o.i % 10 == 1 && !(o.t == 0 && o.i % 100 == 11)) {
    return 'one';
  }
  if (o.t == 0 && o.i % 10 == 2 && !(o.t == 0 && o.i % 100 == 12)) {
    return 'two';
  }
  if (o.t == 0 && o.i % 10 == 3 && !(o.t == 0 && o.i % 100 == 13)) {
    return 'few';
  }
  return 'other';
}

String _ordinal9(PluralOperands o) {
  if (o.t == 0 && (o.i == 1 || o.i == 11)) {
    return 'one';
  }
  if (o.t == 0 && (o.i == 2 || o.i == 12)) {
    return 'two';
  }
  if (o.t == 0 && (o.i == 3 || o.i == 13)) {
    return 'few';
  }
  return 'other';
}

String _ordinal10(PluralOperands o) {
  if (o.t == 0 && o.i == 1) {
    return 'one';
  }
  if (o.t == 0 && (o.i == 2 || o.i == 3)) {
    return 'two';
  }
  if (o.t == 0 && o.i == 4) {
    return 'few';
  }
  if (o.t == 0 && o.i == 6) {
    return 'many';
  }
  return 'other';
}

String _ordinal11(PluralOperands o) {
  if (o.t == 0 && (o.i == 1 || o.i == 5)) {
    return 'one';
  }
  return 'other';
}

String _ordinal12(PluralOperands o) {
  if (o.t == 0 && (o.i == 11 || o.i == 8 || o.i == 80 || o.i == 800)) {
    return 'many';
  }
  return 'other';
}

String _ordinal13(PluralOperands o) {
  if (o.i == 1) {
    return 'one';
  }
  if (o.i == 0 ||
      (((o.i % 100 >= 2 && o.i % 100 <= 20) ||
          o.i % 100 == 40 ||
          o.i % 100 == 60 ||
          o.i % 100 == 80))) {
    return 'many';
  }
  return 'other';
}

String _ordinal14(PluralOperands o) {
  if ((o.t == 0 && o.i % 10 == 6) ||
      (o.t == 0 && o.i % 10 == 9) ||
      (o.t == 0 && o.i % 10 == 0 && !(o.t == 0 && o.i == 0))) {
    return 'many';
  }
  return 'other';
}

String _ordinal15(PluralOperands o) {
  if (o.t == 0 && o.i == 1) {
    return 'one';
  }
  if (o.t == 0 && (o.i == 2 || o.i == 3)) {
    return 'two';
  }
  if (o.t == 0 && o.i == 4) {
    return 'few';
  }
  return 'other';
}

String _ordinal16(PluralOperands o) {
  if ((o.t == 0 && (o.i >= 1 && o.i <= 4)) ||
      (o.t == 0 &&
          ((o.i % 100 >= 1 && o.i % 100 <= 4) ||
              (o.i % 100 >= 21 && o.i % 100 <= 24) ||
              (o.i % 100 >= 41 && o.i % 100 <= 44) ||
              (o.i % 100 >= 61 && o.i % 100 <= 64) ||
              (o.i % 100 >= 81 && o.i % 100 <= 84)))) {
    return 'one';
  }
  if ((o.t == 0 && o.i == 5) || (o.t == 0 && o.i % 100 == 5)) {
    return 'many';
  }
  return 'other';
}

String _ordinal17(PluralOperands o) {
  if (o.t == 0 &&
      (o.i == 11 ||
          o.i == 8 ||
          (o.i >= 80 && o.i <= 89) ||
          (o.i >= 800 && o.i <= 899))) {
    return 'many';
  }
  return 'other';
}

String _ordinal18(PluralOperands o) {
  if (o.i % 10 == 1 && !(o.i % 100 == 11)) {
    return 'one';
  }
  if (o.i % 10 == 2 && !(o.i % 100 == 12)) {
    return 'two';
  }
  if ((o.i % 10 == 7 || o.i % 10 == 8) &&
      !(o.i % 100 == 17 || o.i % 100 == 18)) {
    return 'many';
  }
  return 'other';
}

String _ordinal19(PluralOperands o) {
  if (o.t == 0 && (o.i >= 1 && o.i <= 4)) {
    return 'one';
  }
  return 'other';
}

String _ordinal20(PluralOperands o) {
  if (o.t == 0 && (o.i == 1 || o.i == 5 || (o.i >= 7 && o.i <= 9))) {
    return 'one';
  }
  if (o.t == 0 && (o.i == 2 || o.i == 3)) {
    return 'two';
  }
  if (o.t == 0 && o.i == 4) {
    return 'few';
  }
  if (o.t == 0 && o.i == 6) {
    return 'many';
  }
  return 'other';
}

String _ordinal21(PluralOperands o) {
  if (o.t == 0 && o.i == 1) {
    return 'one';
  }
  if (o.t == 0 && o.i % 10 == 4 && !(o.t == 0 && o.i % 100 == 14)) {
    return 'many';
  }
  return 'other';
}

String _ordinal22(PluralOperands o) {
  if (o.t == 0 &&
      (o.i % 10 == 1 || o.i % 10 == 2) &&
      !(o.t == 0 && (o.i % 100 == 11 || o.i % 100 == 12))) {
    return 'one';
  }
  return 'other';
}

String _ordinal23(PluralOperands o) {
  if ((o.t == 0 && (o.i % 10 == 6 || o.i % 10 == 9)) ||
      (o.t == 0 && o.i == 10)) {
    return 'few';
  }
  return 'other';
}

String _ordinal24(PluralOperands o) {
  if (o.t == 0 && o.i % 10 == 3 && !(o.t == 0 && o.i % 100 == 13)) {
    return 'few';
  }
  return 'other';
}

/// The CLDR ordinal plural rules, by locale.
const ordinalRules = <String, PluralRule>{
  'af': _ordinal0,
  'am': _ordinal0,
  'an': _ordinal0,
  'ar': _ordinal0,
  'as': _ordinal1,
  'ast': _ordinal0,
  'az': _ordinal2,
  'bal': _ordinal3,
  'be': _ordinal4,
  'bg': _ordinal0,
  'blo': _ordinal5,
  'bn': _ordinal1,
  'bs': _ordinal0,
  'ca': _ordinal6,
  'ce': _ordinal0,
  'cs': _ordinal0,
  'cv': _ordinal0,
  'cy': _ordinal7,
  'da': _ordinal0,
  'de': _ordinal0,
  'dsb': _ordinal0,
  'el': _ordinal0,
  'en': _ordinal8,
  'es': _ordinal0,
  'et': _ordinal0,
  'eu': _ordinal0,
  'fa': _ordinal0,
  'fi': _ordinal0,
  'fil': _ordinal3,
  'fr': _ordinal3,
  'fy': _ordinal0,
  'ga': _ordinal3,
  'gd': _ordinal9,
  'gl': _ordinal0,
  'gsw': _ordinal0,
  'gu': _ordinal10,
  'he': _ordinal0,
  'hi': _ordinal10,
  'hr': _ordinal0,
  'hsb': _ordinal0,
  'hu': _ordinal11,
  'hy': _ordinal3,
  'ia': _ordinal0,
  'id': _ordinal0,
  'ie': _ordinal0,
  'is': _ordinal0,
  'it': _ordinal12,
  'ja': _ordinal0,
  'ka': _ordinal13,
  'kk': _ordinal14,
  'km': _ordinal0,
  'kn': _ordinal0,
  'ko': _ordinal0,
  'kok': _ordinal15,
  'kok-Latn': _ordinal15,
  'kw': _ordinal16,
  'ky': _ordinal0,
  'lij': _ordinal17,
  'lld': _ordinal12,
  'lo': _ordinal3,
  'lt': _ordinal0,
  'lv': _ordinal0,
  'mk': _ordinal18,
  'ml': _ordinal0,
  'mn': _ordinal0,
  'mo': _ordinal3,
  'mr': _ordinal15,
  'ms': _ordinal3,
  'my': _ordinal0,
  'nb': _ordinal0,
  'ne': _ordinal19,
  'nl': _ordinal0,
  'no': _ordinal0,
  'or': _ordinal20,
  'pa': _ordinal0,
  'pl': _ordinal0,
  'prg': _ordinal0,
  'ps': _ordinal0,
  'pt': _ordinal0,
  'ro': _ordinal3,
  'ru': _ordinal0,
  'sc': _ordinal12,
  'scn': _ordinal17,
  'sd': _ordinal0,
  'sh': _ordinal0,
  'si': _ordinal0,
  'sk': _ordinal0,
  'sl': _ordinal0,
  'sq': _ordinal21,
  'sr': _ordinal0,
  'sv': _ordinal22,
  'sw': _ordinal0,
  'ta': _ordinal0,
  'te': _ordinal0,
  'th': _ordinal0,
  'tk': _ordinal23,
  'tl': _ordinal3,
  'tpi': _ordinal0,
  'tr': _ordinal0,
  'uk': _ordinal24,
  'und': _ordinal0,
  'ur': _ordinal0,
  'uz': _ordinal0,
  'vec': _ordinal12,
  'vi': _ordinal3,
  'yue': _ordinal0,
  'zh': _ordinal0,
  'zu': _ordinal0,
};
